In [1]:
import numpy as np

# 创建

In [2]:
score = np.array([[80, 89, 86, 67, 79],
          [78, 97, 89, 67, 81],
          [90, 94, 78, 67, 74],
          [91, 91, 90, 67, 69],
          [76, 87, 75, 67, 86],
          [70, 79, 84, 67, 84],
          [94, 92, 93, 67, 64],
          [86, 85, 83, 67, 80]])

In [3]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

# 效率对比

In [4]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())

# 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
%time sum1=sum(a)

b=np.array(a)

%time sum2=np.sum(b)

Wall time: 408 ms
Wall time: 115 ms


# ndarray的属性

In [27]:
score.shape

(8, 5)

In [28]:
score.ndim

2

In [29]:
score.size

40

In [30]:
score.itemsize

4

In [31]:
score.dtype

dtype('int32')

# ndarray的形状

In [32]:
a = np.array([1,2,3])

In [33]:
a

array([1, 2, 3])

In [34]:
b = np.array([[1,2,3],[2,3,4]])

In [35]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [36]:
c = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])

In [37]:
c

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [38]:
a.shape

(3,)

In [39]:
b.shape

(2, 3)

In [40]:
c.shape

(2, 2, 3)

In [41]:
c.ndim

3

In [20]:
a.dtype

dtype('int32')

In [21]:
d = np.array([1,2,3], dtype=np.float32)

In [22]:
d

array([1., 2., 3.], dtype=float32)

In [23]:
a

array([1, 2, 3])

# ndarray的类型

In [24]:
d.dtype

dtype('float32')

In [25]:
e = np.array(["I", "love", "python"], dtype = np.string_)

In [26]:
e

array([b'I', b'love', b'python'], dtype='|S6')

In [8]:
import numpy as np

# 创建
score = np.array([[80, 89, 86, 67, 79],
                  [78, 97, 89, 67, 81],
                  [90, 94, 78, 67, 74],
                  [91, 91, 90, 67, 69],
                  [76, 87, 75, 67, 86],
                  [70, 79, 84, 67, 84],
                  [94, 92, 93, 67, 64],
                  [86, 85, 83, 67, 80]])
print(score)
# [[80 89 86 67 79]
#  [78 97 89 67 81]
#  [90 94 78 67 74]
#  [91 91 90 67 69]
#  [76 87 75 67 86]
#  [70 79 84 67 84]
#  [94 92 93 67 64]
#  [86 85 83 67 80]]

# 数组维度的元组
print(score.shape) # (8, 5)
# 数组维数
print(score.ndim) # 2
#数组中的元素数量
print(score.size) # 40
# 一个数组元素的长度（字节）
print(score.itemsize) #4
#数组元素的类型
print(score.dtype) # int32

[[80 89 86 67 79]
 [78 97 89 67 81]
 [90 94 78 67 74]
 [91 91 90 67 69]
 [76 87 75 67 86]
 [70 79 84 67 84]
 [94 92 93 67 64]
 [86 85 83 67 80]]
(8, 5)
2
40
4
int32


In [1]:
import pandas as pd

In [6]:
tt = pd.read_csv('D:\SqlRelation.csv',encoding='GB2312',delimiter="\t")

In [7]:
tt

记录             三元组                                                SQL  \
0    9.0      客户-申请-申请主体  SELECT  ln_withdrawal_apply.custid,ln_firminfo...   
1   10.0      客户-关联业务-业务  SELECT  ln_withdrawal_apply.custid,ln_withdraw...   
2   11.0    ? 客户-创建人-自然人  SELECT  ln_withdrawal_apply.custid,ln_firminfo...   
3   12.0      客户-修改人-自然人  SELECT  ln_withdrawal_apply.custid,ln_firminfo...   
4   13.0  征信主体―申请/使用―贷记卡  select id,type,name ,creator,updater,lastupdat...   
5   14.0  ? 企业股东-关联业务-业务  select ln_enterprise_stockholder.id, ln_withdr...   
6   15.0    企业股东-创建人-自然人  select ln_enterprise_stockholder.id,ln_enterpr...   
7   16.0    企业股东-修改人-自然人  select ln_enterprise_stockholder.id,ln_enterpr...   
8    NaN             NaN                                                NaN   
9    NaN             NaN                                                NaN   
10   NaN             NaN                                                NaN   
11   NaN             NaN                                                NaN   
12   NaN             NaN                                                NaN   
13   NaN             NaN                                                NaN   
14   NaN             NaN                                                NaN   
15   NaN             NaN                                                NaN   
16   NaN             NaN                                                NaN   
17   NaN             NaN                                                NaN   
18   NaN             NaN                                                NaN   
19   NaN             NaN                                                NaN   

      HEADENTITY          TAILENTITY  \
0       Customer             Subject   
1       Customer            Business   
2       Customer       NaturalPerson   
3       Customer       NaturalPerson   
4   CreditEntity                 NaN   
5    Stockholder            Business   
6    Stockholder       NaturalPerson   
7    Stockholder       NaturalPerson   
8            NaN                 NaN   
9            NaN                 NaN   
10           NaN                 NaN   
11           NaN                 NaN   
12            备注                 NaN   
13           NaN                 NaN   
14           NaN             自创客户实体：   
15           NaN              自创申请主体   
16           NaN  ? 客户-创建人-自然人：自然人实体   
17           NaN    客户-修改人-自然人：自然人实体   
18           NaN  企业股东-创建人-自然人：自然人实体   
19           NaN  企业股东-修改人-自然人：自然人实体   

                                         RELATIONNAME  \
0                                                  申请   
1                                                关联业务   
2                                                 创建人   
3                                                 修改人   
4                                               申请/使用   
5                                                关联业务   
6                                                 创建人   
7                                                 修改人   
8                                                 NaN   
9                                                 NaN   
10                                                NaN   
11                                                NaN   
12  黄色标记为自创实体，主要是自然人和申请主体以及客户实体在实体表中没有，其tkey和taile...   
13                        红色部分为贷记卡实体缺失，没有找到贷记卡实体的唯一标志   
14  SELECT  ln_withdrawal_apply.custid,ln_firminfo...   
15  SELECT  ln_firminfo_snapshot.subjectcanumber,s...   
16  SELECT  ln_firminfo_snapshot.creatorid,ln_firm...   
17  SELECT  ln_firminfo_snapshot.updaterid,ln_firm...   
18  select ln_enterprise_stockholder.creatorid,ln_...   
19  select ln_enterprise_stockholder.updaterid,ln_...   

                          HKEY                                  TKEY  \
0   ln_withdrawal_apply.custid  ln_firminfo_snapshot.subjectcanumber   
1   ln_withdrawal_apply.custid                           ApplyUserID   
2   ln_withdrawal_apply.custid        ln_firminfo_snapshot.creatorid   
3   ln_withdrawal_a

In [8]:
tt.to_csv('D:/yjz.csv',encoding='GB2312')

In [9]:
tt.to_excel('D:/yjz123.xlsx')