In [1]:
import numpy as np

# 创建

In [2]:
score = np.array([[80, 89, 86, 67, 79],
          [78, 97, 89, 67, 81],
          [90, 94, 78, 67, 74],
          [91, 91, 90, 67, 69],
          [76, 87, 75, 67, 86],
          [70, 79, 84, 67, 84],
          [94, 92, 93, 67, 64],
          [86, 85, 83, 67, 80]])

In [3]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

# 效率对比

In [4]:
import random
import time
import numpy as np
a = []
for i in range(100000000):
    a.append(random.random())

# 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
%time sum1=sum(a)

b=np.array(a)

%time sum2=np.sum(b)

Wall time: 408 ms
Wall time: 115 ms


# ndarray的属性

In [27]:
score.shape

(8, 5)

In [28]:
score.ndim

2

In [29]:
score.size

40

In [30]:
score.itemsize

4

In [31]:
score.dtype

dtype('int32')

# ndarray的形状

In [32]:
a = np.array([1,2,3])

In [33]:
a

array([1, 2, 3])

In [34]:
b = np.array([[1,2,3],[2,3,4]])

In [35]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [36]:
c = np.array([[[1,2,3],[2,3,4]],[[3,4,5],[4,5,6]]])

In [37]:
c

array([[[1, 2, 3],
        [2, 3, 4]],

       [[3, 4, 5],
        [4, 5, 6]]])

In [38]:
a.shape

(3,)

In [39]:
b.shape

(2, 3)

In [40]:
c.shape

(2, 2, 3)

In [41]:
c.ndim

3

In [20]:
a.dtype

dtype('int32')

In [21]:
d = np.array([1,2,3], dtype=np.float32)

In [22]:
d

array([1., 2., 3.], dtype=float32)

In [23]:
a

array([1, 2, 3])

# ndarray的类型

In [24]:
d.dtype

dtype('float32')

In [25]:
e = np.array(["I", "love", "python"], dtype = np.string_)

In [26]:
e

array([b'I', b'love', b'python'], dtype='|S6')