In [1]:
import numpy as np

# 逻辑运算

In [3]:
stock_change = np.random.normal(0, 1, (8, 10))

In [4]:
stock_change

array([[-0.39683594, -0.93282904, -1.02920753, -0.29748756, -0.3680078 ,
         0.98140878, -0.81723545,  0.56047523, -0.80833788, -0.09010658],
       [ 0.22499774,  0.45662551,  0.35473895, -1.03158314, -0.41552147,
        -1.11736653, -0.22939103,  0.51764552,  0.24643008,  1.17599063],
       [ 1.53088066, -2.49918097, -0.44873299, -0.47364179,  1.21705411,
         0.89417842, -0.53344331,  2.46632174,  1.45489068,  1.17761271],
       [-0.604213  ,  0.73868167,  0.76286223, -0.14759815, -0.21141578,
        -2.26995168,  0.23460968, -0.99904004,  0.17889611,  0.78854751],
       [-1.26828728, -0.51387828,  2.65921615,  1.06558291,  2.64857772,
        -0.28108191, -1.9654477 ,  0.60141932, -0.48091659, -1.65436784],
       [-0.47906913,  0.4254376 ,  0.69262436, -0.10114936,  2.04621752,
         1.32452259, -0.17739464, -2.76271823, -0.74636209, -0.48365622],
       [ 0.23643417,  1.52592047,  0.17615198, -0.84678785, -0.83293422,
        -0.88591975,  1.81768892,  0.11440743

In [5]:
stock_c = stock_change[0:5, 0:5]

In [6]:
stock_c

array([[-0.39683594, -0.93282904, -1.02920753, -0.29748756, -0.3680078 ],
       [ 0.22499774,  0.45662551,  0.35473895, -1.03158314, -0.41552147],
       [ 1.53088066, -2.49918097, -0.44873299, -0.47364179,  1.21705411],
       [-0.604213  ,  0.73868167,  0.76286223, -0.14759815, -0.21141578],
       [-1.26828728, -0.51387828,  2.65921615,  1.06558291,  2.64857772]])

In [7]:
stock_c > 1

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [ True, False, False, False,  True],
       [False, False, False, False, False],
       [False, False,  True,  True,  True]])

In [8]:
stock_c[stock_c >1] = 2

In [9]:
stock_c

array([[-0.39683594, -0.93282904, -1.02920753, -0.29748756, -0.3680078 ],
       [ 0.22499774,  0.45662551,  0.35473895, -1.03158314, -0.41552147],
       [ 2.        , -2.49918097, -0.44873299, -0.47364179,  2.        ],
       [-0.604213  ,  0.73868167,  0.76286223, -0.14759815, -0.21141578],
       [-1.26828728, -0.51387828,  2.        ,  2.        ,  2.        ]])

In [10]:
test_a = [1,2,3]

In [12]:
# test_a > 2

In [14]:
stock_d = stock_change[0:2, 0:5]

In [15]:
stock_d

array([[-0.39683594, -0.93282904, -1.02920753, -0.29748756, -0.3680078 ],
       [ 0.22499774,  0.45662551,  0.35473895, -1.03158314, -0.41552147]])

In [17]:
np.all(stock_d > 0)

False

In [19]:
np.any(stock_d>0)

True

In [20]:
np.where(stock_d>0, 1, 0)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [21]:
np.where(np.logical_and(stock_d>-0.5, stock_d<0.5), 1, 0)

array([[1, 0, 0, 1, 1],
       [1, 1, 1, 0, 1]])

In [22]:
np.where(np.logical_or(stock_d>0, stock_d<-1), 2, 0)

array([[0, 0, 2, 0, 0],
       [2, 2, 2, 2, 0]])

In [24]:
stock_change

array([[-0.39683594, -0.93282904, -1.02920753, -0.29748756, -0.3680078 ,
         0.98140878, -0.81723545,  0.56047523, -0.80833788, -0.09010658],
       [ 0.22499774,  0.45662551,  0.35473895, -1.03158314, -0.41552147,
        -1.11736653, -0.22939103,  0.51764552,  0.24643008,  1.17599063],
       [ 2.        , -2.49918097, -0.44873299, -0.47364179,  2.        ,
         0.89417842, -0.53344331,  2.46632174,  1.45489068,  1.17761271],
       [-0.604213  ,  0.73868167,  0.76286223, -0.14759815, -0.21141578,
        -2.26995168,  0.23460968, -0.99904004,  0.17889611,  0.78854751],
       [-1.26828728, -0.51387828,  2.        ,  2.        ,  2.        ,
        -0.28108191, -1.9654477 ,  0.60141932, -0.48091659, -1.65436784],
       [-0.47906913,  0.4254376 ,  0.69262436, -0.10114936,  2.04621752,
         1.32452259, -0.17739464, -2.76271823, -0.74636209, -0.48365622],
       [ 0.23643417,  1.52592047,  0.17615198, -0.84678785, -0.83293422,
        -0.88591975,  1.81768892,  0.11440743

In [26]:
stock_change.max(axis=0)

array([2.        , 1.52592047, 2.        , 2.        , 2.04621752,
       2.43803372, 1.81768892, 2.46632174, 1.45489068, 1.61846178])

In [28]:
stock_c

array([[-0.39683594, -0.93282904, -1.02920753, -0.29748756, -0.3680078 ],
       [ 0.22499774,  0.45662551,  0.35473895, -1.03158314, -0.41552147],
       [ 2.        , -2.49918097, -0.44873299, -0.47364179,  2.        ],
       [-0.604213  ,  0.73868167,  0.76286223, -0.14759815, -0.21141578],
       [-1.26828728, -0.51387828,  2.        ,  2.        ,  2.        ]])

In [30]:
stock_c.argmax(axis=1)

array([3, 1, 0, 2, 2])

In [31]:
stock_c.argmax(axis=0)

array([2, 3, 4, 4, 2])

In [32]:
stock_c.argmin(axis=1)

array([2, 3, 1, 0, 0])

# 数组运算

In [33]:
arr = np.array([1,2,3,4])

In [34]:
arr

array([1, 2, 3, 4])

In [35]:
arr+1

array([2, 3, 4, 5])

In [36]:
arr/2

array([0.5, 1. , 1.5, 2. ])

In [37]:
arr*10

array([10, 20, 30, 40])

In [38]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1, 2, 3, 4], [3, 4, 5, 6]])

In [40]:
# arr1+arr2 不可以运算

In [41]:
arr1 = np.array([[1, 2, 3, 2, 1, 4], [5, 6, 1, 2, 3, 1]])
arr2 = np.array([[1], [3]])

In [42]:
arr1+arr2

array([[2, 3, 4, 3, 2, 5],
       [8, 9, 4, 5, 6, 4]])

In [44]:
a = np.array([[80, 86],
              [82, 80],
              [85, 78],
              [90, 90],
              [86, 82],
              [82, 90],
              [78, 80],
              [92, 94]])

In [45]:
b = np.array([[0.7], [0.3]])

In [46]:
np.matmul(a, b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [47]:
np.dot(a,b)

array([[81.8],
       [81.4],
       [82.9],
       [90. ],
       [84.8],
       [84.4],
       [78.6],
       [92.6]])

In [48]:
np.dot(a, 10)

array([[800, 860],
       [820, 800],
       [850, 780],
       [900, 900],
       [860, 820],
       [820, 900],
       [780, 800],
       [920, 940]])

In [51]:
# np.matmul(a, 10) # matmul不支持矩阵和数字的相乘