In [ ]:
# Numpy（Numerical Python）是一个开源的Python科学计算库，用于快速处理任意维度的数组。

In [5]:
import numpy as np

In [6]:
# 创建数组
lst = [[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]]
score = np.array(lst)

In [7]:
score

array([[80, 89, 86, 67, 79],
       [78, 97, 89, 67, 81],
       [90, 94, 78, 67, 74],
       [91, 91, 90, 67, 69],
       [76, 87, 75, 67, 86],
       [70, 79, 84, 67, 84],
       [94, 92, 93, 67, 64],
       [86, 85, 83, 67, 80]])

# ndarray与Python原生list运算效率对比

In [11]:
import random
import time
import numpy as np

In [12]:
a = []
for i in range(1000000):
    a.append(random.random())

# 通过%time魔法方法, 查看当前行的代码运行一次所花费的时间
%time sum1 = sum(a)
b = np.array(a)
%time sum2 = np.sum(b)

Wall time: 3.99 ms
Wall time: 998 µs


# ndayray的属性

In [13]:
 a = np.array([[1,2,3],[4,5,6]])
 b = np.array([1,2,3,4])
 c = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

In [14]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
b

array([1, 2, 3, 4])

In [16]:
c

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [17]:
a.shape

(2, 3)

In [18]:
b.shape

(4,)

In [19]:
c.shape

(2, 2, 3)

In [27]:
print("数组维数a=%d,b=%d,c=%d" % (a.ndim,b.ndim,c.ndim))

数组维数a=2,b=1,c=3


In [28]:
print("数组元素数量为：a=%d,b=%d,c=%d" % (a.size,b.size,c.size))

数组元素数量为：a=6,b=4,c=12


In [29]:
print("数组元素类型：a=%s,b=%s,c=%s" % (a.dtype,b.dtype,c.dtype))

数组元素类型：a=int32,b=int32,c=int32


In [30]:
np.ones([4,8])

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [31]:
np.ones([4,8],np.string_)

array([[b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1'],
       [b'1', b'1', b'1', b'1', b'1', b'1', b'1', b'1']], dtype='|S1')

In [60]:
score = np.random.randint(40, 100, (10, 5))

In [61]:
score

array([[41, 91, 83, 65, 44],
       [85, 82, 55, 40, 99],
       [57, 76, 63, 73, 78],
       [57, 60, 43, 57, 40],
       [56, 83, 80, 80, 64],
       [73, 49, 73, 97, 51],
       [68, 65, 88, 85, 76],
       [89, 43, 77, 98, 58],
       [43, 53, 58, 97, 49],
       [73, 67, 48, 51, 69]])

In [53]:
temp_score = score

In [54]:
score[9][1:5]

array([63, 74, 41, 82])

In [55]:
score > 60

array([[ True,  True,  True, False,  True],
       [False,  True, False, False,  True],
       [ True,  True, False, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [ True,  True,  True,  True, False],
       [ True,  True,  True, False,  True]])

In [56]:
temp_score[temp_score > 60] = 1

In [58]:
temp_score

array([[ 1,  1,  1, 45,  1],
       [44,  1, 47, 53,  1],
       [ 1,  1, 44, 47,  1],
       [ 1,  1, 56,  1,  1],
       [60,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1,  1, 41,  1,  1],
       [ 1,  1,  1,  1, 52],
       [ 1,  1,  1, 41,  1]])

In [62]:
score

array([[41, 91, 83, 65, 44],
       [85, 82, 55, 40, 99],
       [57, 76, 63, 73, 78],
       [57, 60, 43, 57, 40],
       [56, 83, 80, 80, 64],
       [73, 49, 73, 97, 51],
       [68, 65, 88, 85, 76],
       [89, 43, 77, 98, 58],
       [43, 53, 58, 97, 49],
       [73, 67, 48, 51, 69]])

In [63]:
np.all(score < 60)

False

In [64]:
np.any(score <
       60)

True

In [65]:
temp = score

In [66]:
np.where(temp>60,1,0)

array([[0, 1, 1, 1, 0],
       [1, 1, 0, 0, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0],
       [1, 1, 0, 0, 1]])

In [67]:
temp

array([[41, 91, 83, 65, 44],
       [85, 82, 55, 40, 99],
       [57, 76, 63, 73, 78],
       [57, 60, 43, 57, 40],
       [56, 83, 80, 80, 64],
       [73, 49, 73, 97, 51],
       [68, 65, 88, 85, 76],
       [89, 43, 77, 98, 58],
       [43, 53, 58, 97, 49],
       [73, 67, 48, 51, 69]])

In [68]:
# 判断前四名学生,前四门课程中，成绩中大于60且小于90的换为1，否则为0
np.where(np.logical_and(temp > 60, temp < 90), 1, 0)

array([[0, 0, 1, 1, 0],
       [1, 1, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1],
       [1, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 1, 0, 0, 1]])

In [69]:
# 判断前四名学生,前四门课程中，成绩中大于90或小于60的换为1，否则为0
np.where(np.logical_or(temp > 90, temp < 60), 1, 0)

array([[1, 1, 0, 0, 1],
       [0, 0, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [1, 0, 1, 1, 1],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [0, 1, 0, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 1, 0]])

In [70]:
score

array([[41, 91, 83, 65, 44],
       [85, 82, 55, 40, 99],
       [57, 76, 63, 73, 78],
       [57, 60, 43, 57, 40],
       [56, 83, 80, 80, 64],
       [73, 49, 73, 97, 51],
       [68, 65, 88, 85, 76],
       [89, 43, 77, 98, 58],
       [43, 53, 58, 97, 49],
       [73, 67, 48, 51, 69]])

In [73]:
print("前四名学生,各科成绩的最大分：{}".format(np.max(score, axis=0)))

前四名学生,各科成绩的最大分：[89 91 88 98 99]


In [74]:
np.max(score,1)

array([91, 99, 78, 60, 83, 97, 88, 98, 97, 73])

In [79]:
arr1 = np.array([[1, 2, 3, 2], [5, 6, 1, 2]])
arr2 = np.array([[1,2],[2,3],[3,4],[4,5]])


In [80]:
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

In [81]:
arr1 = np.array([[0],[1],[2],[3]])

In [82]:
arr1

array([[0],
       [1],
       [2],
       [3]])

In [83]:
arr1.shape

(4, 1)

In [84]:
arr2 = np.array([1,2,3])

In [85]:
arr2.shape

(3,)

In [86]:
arr2.ndim

1

In [87]:
arr2

array([1, 2, 3])

In [88]:
arr1 + arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [89]:
arr1 * arr2

array([[0, 0, 0],
       [1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [ ]:
data = pd.read_csv("./data/stock_day.csv")