In [2]:
import pandas as pd
import numpy as np

# pandas案例导入

In [3]:
stock_change = np.random.normal(0, 1, (10, 5))

In [4]:
stock_change

array([[ 0.72455213, -0.55197053,  0.14968459,  2.10203877, -0.35704243],
       [ 1.51449272, -1.01670173,  2.47426194,  1.90482948, -0.14937936],
       [ 1.54082579, -0.59384168,  0.68835082, -0.08637503, -0.74575723],
       [-0.89002436,  0.42222628,  0.09177474, -0.08150815,  2.29722099],
       [-1.24582423, -2.03447035,  0.86399373, -0.58584514,  0.91124687],
       [-0.11204875, -0.42721468,  0.6869972 , -0.95331018,  1.70683535],
       [ 0.01222896, -1.76543205, -1.01863175, -0.08070972, -1.57987936],
       [-0.40872634,  1.1841661 , -0.55080283, -0.03962603, -0.39539714],
       [ 0.46211836,  0.06804112, -0.1206769 , -1.67268873, -0.04697773],
       [ 0.47121349,  0.17117592,  1.5188797 ,  0.98378977,  1.14318528]])

In [6]:
stock_rise = pd.DataFrame(stock_change)

In [7]:
stock_rise

0         1         2         3         4
0  0.724552 -0.551971  0.149685  2.102039 -0.357042
1  1.514493 -1.016702  2.474262  1.904829 -0.149379
2  1.540826 -0.593842  0.688351 -0.086375 -0.745757
3 -0.890024  0.422226  0.091775 -0.081508  2.297221
4 -1.245824 -2.034470  0.863994 -0.585845  0.911247
5 -0.112049 -0.427215  0.686997 -0.953310  1.706835
6  0.012229 -1.765432 -1.018632 -0.080710 -1.579879
7 -0.408726  1.184166 -0.550803 -0.039626 -0.395397
8  0.462118  0.068041 -0.120677 -1.672689 -0.046978
9  0.471213  0.171176  1.518880  0.983790  1.143185

In [11]:
stock_rise.shape[0]

10

In [12]:
stock_code = ["股票{}".format(i+1) for i in range(stock_rise.shape[0])]

In [13]:
stock_code

['股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9', '股票10']

In [16]:
pd.DataFrame(stock_change, index=stock_code)

0         1         2         3         4
股票1   0.724552 -0.551971  0.149685  2.102039 -0.357042
股票2   1.514493 -1.016702  2.474262  1.904829 -0.149379
股票3   1.540826 -0.593842  0.688351 -0.086375 -0.745757
股票4  -0.890024  0.422226  0.091775 -0.081508  2.297221
股票5  -1.245824 -2.034470  0.863994 -0.585845  0.911247
股票6  -0.112049 -0.427215  0.686997 -0.953310  1.706835
股票7   0.012229 -1.765432 -1.018632 -0.080710 -1.579879
股票8  -0.408726  1.184166 -0.550803 -0.039626 -0.395397
股票9   0.462118  0.068041 -0.120677 -1.672689 -0.046978
股票10  0.471213  0.171176  1.518880  0.983790  1.143185

In [19]:
date = pd.date_range(start="20190403", periods=stock_rise.shape[1], freq="B")

In [20]:
date

DatetimeIndex(['2019-04-03', '2019-04-04', '2019-04-05', '2019-04-08',
               '2019-04-09'],
              dtype='datetime64[ns]', freq='B')

In [22]:
stock_c = pd.DataFrame(stock_change, index=stock_code, columns=date)

# DataFrame

In [23]:
stock_c

2019-04-03  2019-04-04  2019-04-05  2019-04-08  2019-04-09
股票1     0.724552   -0.551971    0.149685    2.102039   -0.357042
股票2     1.514493   -1.016702    2.474262    1.904829   -0.149379
股票3     1.540826   -0.593842    0.688351   -0.086375   -0.745757
股票4    -0.890024    0.422226    0.091775   -0.081508    2.297221
股票5    -1.245824   -2.034470    0.863994   -0.585845    0.911247
股票6    -0.112049   -0.427215    0.686997   -0.953310    1.706835
股票7     0.012229   -1.765432   -1.018632   -0.080710   -1.579879
股票8    -0.408726    1.184166   -0.550803   -0.039626   -0.395397
股票9     0.462118    0.068041   -0.120677   -1.672689   -0.046978
股票10    0.471213    0.171176    1.518880    0.983790    1.143185

In [24]:
stock_c.shape

(10, 5)

In [25]:
stock_c.index

Index(['股票1', '股票2', '股票3', '股票4', '股票5', '股票6', '股票7', '股票8', '股票9', '股票10'], dtype='object')

In [26]:
stock_c.columns

DatetimeIndex(['2019-04-03', '2019-04-04', '2019-04-05', '2019-04-08',
               '2019-04-09'],
              dtype='datetime64[ns]', freq='B')

In [27]:
stock_c.values

array([[ 0.72455213, -0.55197053,  0.14968459,  2.10203877, -0.35704243],
       [ 1.51449272, -1.01670173,  2.47426194,  1.90482948, -0.14937936],
       [ 1.54082579, -0.59384168,  0.68835082, -0.08637503, -0.74575723],
       [-0.89002436,  0.42222628,  0.09177474, -0.08150815,  2.29722099],
       [-1.24582423, -2.03447035,  0.86399373, -0.58584514,  0.91124687],
       [-0.11204875, -0.42721468,  0.6869972 , -0.95331018,  1.70683535],
       [ 0.01222896, -1.76543205, -1.01863175, -0.08070972, -1.57987936],
       [-0.40872634,  1.1841661 , -0.55080283, -0.03962603, -0.39539714],
       [ 0.46211836,  0.06804112, -0.1206769 , -1.67268873, -0.04697773],
       [ 0.47121349,  0.17117592,  1.5188797 ,  0.98378977,  1.14318528]])

In [28]:
stock_c.T

股票1       股票2       股票3       股票4       股票5       股票6  \
2019-04-03  0.724552  1.514493  1.540826 -0.890024 -1.245824 -0.112049   
2019-04-04 -0.551971 -1.016702 -0.593842  0.422226 -2.034470 -0.427215   
2019-04-05  0.149685  2.474262  0.688351  0.091775  0.863994  0.686997   
2019-04-08  2.102039  1.904829 -0.086375 -0.081508 -0.585845 -0.953310   
2019-04-09 -0.357042 -0.149379 -0.745757  2.297221  0.911247  1.706835   

                 股票7       股票8       股票9      股票10  
2019-04-03  0.012229 -0.408726  0.462118  0.471213  
2019-04-04 -1.765432  1.184166  0.068041  0.171176  
2019-04-05 -1.018632 -0.550803 -0.120677  1.518880  
2019-04-08 -0.080710 -0.039626 -1.672689  0.983790  
2019-04-09 -1.579879 -0.395397 -0.046978  1.143185

In [33]:
stock_c.head()

2019-04-03  2019-04-04  2019-04-05  2019-04-08  2019-04-09
股票1    0.724552   -0.551971    0.149685    2.102039   -0.357042
股票2    1.514493   -1.016702    2.474262    1.904829   -0.149379
股票3    1.540826   -0.593842    0.688351   -0.086375   -0.745757
股票4   -0.890024    0.422226    0.091775   -0.081508    2.297221
股票5   -1.245824   -2.034470    0.863994   -0.585845    0.911247

In [35]:
stock_c.tail(3)

2019-04-03  2019-04-04  2019-04-05  2019-04-08  2019-04-09
股票8    -0.408726    1.184166   -0.550803   -0.039626   -0.395397
股票9     0.462118    0.068041   -0.120677   -1.672689   -0.046978
股票10    0.471213    0.171176    1.518880    0.983790    1.143185

##  设置索引

In [36]:
stock_code = ["股票__{}".format(i+1) for i in range(stock_rise.shape[0])]

In [41]:
stock_c.index = stock_code

In [42]:
stock_c

2019-04-03  2019-04-04  2019-04-05  2019-04-08  2019-04-09
股票__1     0.724552   -0.551971    0.149685    2.102039   -0.357042
股票__2     1.514493   -1.016702    2.474262    1.904829   -0.149379
股票__3     1.540826   -0.593842    0.688351   -0.086375   -0.745757
股票__4    -0.890024    0.422226    0.091775   -0.081508    2.297221
股票__5    -1.245824   -2.034470    0.863994   -0.585845    0.911247
股票__6    -0.112049   -0.427215    0.686997   -0.953310    1.706835
股票__7     0.012229   -1.765432   -1.018632   -0.080710   -1.579879
股票__8    -0.408726    1.184166   -0.550803   -0.039626   -0.395397
股票__9     0.462118    0.068041   -0.120677   -1.672689   -0.046978
股票__10    0.471213    0.171176    1.518880    0.983790    1.143185

In [45]:
# stock_c.index[3] = "hahaha"

## 重设索引

In [46]:
stock_c.reset_index()

index  2019-04-03 00:00:00  2019-04-04 00:00:00  2019-04-05 00:00:00  \
0   股票__1             0.724552            -0.551971             0.149685   
1   股票__2             1.514493            -1.016702             2.474262   
2   股票__3             1.540826            -0.593842             0.688351   
3   股票__4            -0.890024             0.422226             0.091775   
4   股票__5            -1.245824            -2.034470             0.863994   
5   股票__6            -0.112049            -0.427215             0.686997   
6   股票__7             0.012229            -1.765432            -1.018632   
7   股票__8            -0.408726             1.184166            -0.550803   
8   股票__9             0.462118             0.068041            -0.120677   
9  股票__10             0.471213             0.171176             1.518880   

   2019-04-08 00:00:00  2019-04-09 00:00:00  
0             2.102039            -0.357042  
1             1.904829            -0.149379  
2            -0.086375            -0.745757  
3            -0.081508             2.297221  
4            -0.585845             0.911247  
5            -0.953310             1.706835  
6            -0.080710            -1.579879  
7            -0.039626            -0.395397  
8            -1.672689            -0.046978  
9             0.983790             1.143185

In [47]:
stock_c.reset_index(drop=True)

2019-04-03  2019-04-04  2019-04-05  2019-04-08  2019-04-09
0    0.724552   -0.551971    0.149685    2.102039   -0.357042
1    1.514493   -1.016702    2.474262    1.904829   -0.149379
2    1.540826   -0.593842    0.688351   -0.086375   -0.745757
3   -0.890024    0.422226    0.091775   -0.081508    2.297221
4   -1.245824   -2.034470    0.863994   -0.585845    0.911247
5   -0.112049   -0.427215    0.686997   -0.953310    1.706835
6    0.012229   -1.765432   -1.018632   -0.080710   -1.579879
7   -0.408726    1.184166   -0.550803   -0.039626   -0.395397
8    0.462118    0.068041   -0.120677   -1.672689   -0.046978
9    0.471213    0.171176    1.518880    0.983790    1.143185

## 以某列设置新的索引

In [48]:
df = pd.DataFrame({'month': [1, 4, 7, 10],
                    'year': [2012, 2014, 2013, 2014],
                    'sale':[55, 40, 84, 31]})

In [49]:
df

month  sale  year
0      1    55  2012
1      4    40  2014
2      7    84  2013
3     10    31  2014

In [50]:
df.set_index(keys=["year"])

month  sale
year             
2012      1    55
2014      4    40
2013      7    84
2014     10    31

In [53]:
df = df.set_index(keys=["year", "month"])

# MultiIndex和panel

## MultiIndex

In [54]:
df

sale
year month      
2012 1        55
2014 4        40
2013 7        84
2014 10       31

In [55]:
df.index

MultiIndex(levels=[[2012, 2013, 2014], [1, 4, 7, 10]],
           labels=[[0, 2, 1, 2], [0, 1, 2, 3]],
           names=['year', 'month'])

In [56]:
df.index.names

FrozenList(['year', 'month'])

In [57]:
df.index.levels

FrozenList([[2012, 2013, 2014], [1, 4, 7, 10]])

## panel

In [58]:
np.arange(24).reshape(4,3,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [59]:
p = pd.Panel(np.arange(24).reshape(4,3,2),
                 items=list('ABCD'),
                 major_axis=pd.date_range('20130101', periods=3),
                 minor_axis=['first', 'second'])

In [60]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 4 (items) x 3 (major_axis) x 2 (minor_axis)
Items axis: A to D
Major_axis axis: 2013-01-01 00:00:00 to 2013-01-03 00:00:00
Minor_axis axis: first to second

In [62]:
p[:,:,"first"]

A   B   C   D
2013-01-01  0   6  12  18
2013-01-02  2   8  14  20
2013-01-03  4  10  16  22

In [63]:
p["A", :, :]

first  second
2013-01-01      0       1
2013-01-02      2       3
2013-01-03      4       5

# series

In [66]:
type(stock_c["2019-04-03"])

pandas.core.series.Series

In [69]:
stock_c

2019-04-03  2019-04-04  2019-04-05  2019-04-08  2019-04-09
股票__1     0.724552   -0.551971    0.149685    2.102039   -0.357042
股票__2     1.514493   -1.016702    2.474262    1.904829   -0.149379
股票__3     1.540826   -0.593842    0.688351   -0.086375   -0.745757
股票__4    -0.890024    0.422226    0.091775   -0.081508    2.297221
股票__5    -1.245824   -2.034470    0.863994   -0.585845    0.911247
股票__6    -0.112049   -0.427215    0.686997   -0.953310    1.706835
股票__7     0.012229   -1.765432   -1.018632   -0.080710   -1.579879
股票__8    -0.408726    1.184166   -0.550803   -0.039626   -0.395397
股票__9     0.462118    0.068041   -0.120677   -1.672689   -0.046978
股票__10    0.471213    0.171176    1.518880    0.983790    1.143185

In [71]:
stock_c["2019-04-03"]["股票__1"]

0.7245521299066583

In [73]:
pd.Series(np.arange(10))

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [74]:
pd.Series([6.7,5.6,3,10,2], index=[1,2,3,4,5])

1     6.7
2     5.6
3     3.0
4    10.0
5     2.0
dtype: float64

In [76]:
series_demo = pd.Series({"red":10, "green":20})

In [77]:
series_demo.index

Index(['green', 'red'], dtype='object')

In [78]:
series_demo.values

array([20, 10])